[packages.homebrew]
    [packages.homebrew.common]
        casks = [
            "1password",
            "1password-cli",
            "docker",
            "gitkraken",
            "iterm2",                        # Terminal emulator
            "visual-studio-code",
        ]
        formulae = [
            "atuin",           # Better shell history
            "bat",             # cat with syntax highlighting and Git integration
            "chezmoi",         # Dotfile manager
            "coreutils",
            "corretto@21",
            "eza",             # ls replacement
            "fd",              # fd-find
            "findutils",       # GNU find, locate, updatedb, and xargs
            "fzf",             # Fuzzy finder
            "gawk",            # GNU awk
            "git",
            "gping",           # Ping, but with a graph
            "grep",
            "jq",              # Lightweight and flexible command-line JSON processor
            "mas",             # Mac App Store command-line interface
            "maven@3.8",
            "ssh-copy-id",     # Add a public key to a remote machine's authorized_keys file
            "tree",            # Display directories as trees (with optional color/HTML output)
            "vivid",           # https://github.com/sharkdp/vivid
            "wget",
            "zoxide",          # A faster way to navigate your filesystem
        ]
    [packages.homebrew.personal_computer]
        casks = [
            "google-chrome",
            "obsidian",
            "slack",
            "spotify",
            "whatsapp",
        ]
        formulae = []
[packages.mas]
    [packages.mas.common]
        apps = []
    [packages.mas.personal_computer]
        apps = []
